//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reception.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListDopService
    {
        public int ID { get; set; }
        public int ServiceID { get; set; }
        public int CheckInID { get; set; }
        public System.DateTime DayStart { get; set; }
        public System.DateTime DayOver { get; set; }
    
        public virtual CheckIn CheckIn { get; set; }
        public virtual Service Service { get; set; }
    }
}
